# Generated by Django 5.1.6 on 2025-02-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('caretaker', 'Caretaker'), ('patient', 'Patient')], max_length=10),
        ),
    ]
