# Generated by Django 5.1.6 on 2025-02-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_node_image_alter_node_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
